global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'node'
    scrape_interval: 5s
    scheme: https
    metrics_path: /metrics
    static_configs:
      - targets:
        - 'node-exporter.epic.uat.app.esmagico.in'
  
  - job_name: 'cadvisor'
    scrape_interval: 15s
    scheme: https
    metrics_path: /metrics
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: 
        - 'cadvisor.epic.uat.app.esmagico.in'
  
  - job_name: 'kong'
    scrape_interval: 5s
    scheme: https
    metrics_path: /metrics
    static_configs:
      - targets: ['kong-admin.epic.uat.app.esmagico.in']
    tls_config:
      insecure_skip_verify: true