server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki.epicglobalinc.com/loki/api/v1/push
    tls_config:
      insecure_skip_verify: true  

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: container_name

      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: compose_service

      - source_labels: [__meta_docker_container_label_com_docker_compose_project]
        target_label: compose_project

      - source_labels: [__meta_docker_container_id]
        target_label: container_id

    pipeline_stages:
      - json:
          expressions:
            log: log
            time: time

      - timestamp:
          format: RFC3339Nano
          source: time

      - output:
          source: log