include:
  - ./common/monitoring/prod/docker-compose.core-stack.yaml

services:
  caddy:
    extends:
      file: ./common/caddy/docker-compose.yaml
      service: caddy
    volumes:
      - ./caddyfile-overrides/prod/Caddyfile.prod-infra:/etc/caddy/Caddyfile
volumes:
  caddy_data:
  caddy_config:
