services:
  redis:
    image: redis:latest
    restart: always
    networks: 
      - backend_network
    command: [ 'redis-server', '--appendonly', 'yes' ]
    volumes:
      - redis:/data
      - redis_conf:/usr/local/etc/redis/redis.conf

volumes:
  redis:
  redis_conf:
