services:
  db:
    image: postgres:17.2
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
      - ./postgres_conf/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres_conf/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./postgres_conf/ssl/server.crt:/etc/postgresql/server.crt
      - ./postgres_conf/ssl/server.key:/etc/postgresql/server.key
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?POSTGRES_USER is not set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is not set}
      POSTGRES_DB: ${POSTGRES_DB:?POSTGRES_DB is not set}


volumes:
  db:
